DG: false
FSGD: false
PCB: false
adv: 0.0
aiter: 10
arcface: false
batchsize: 8
circle: true
color_jitter: false
contrast: false
cosface: false
cosine: false
data_dir: ../Market/pytorch
droprate: 0.5
erasing_p: 0.5
fp16: false
gpu_ids:
- 0
ibn: false
ins_gamma: 32
instance: false
lifted: false
linear_num: 512
lr: 0.02
name: warm5_s1_b8_lr2_p0.5_circle
nclasses: 751
sphere: false
stride: 1
total_epoch: 60
train_all: false
triplet: false
use_NAS: false
use_convnext: false
use_dense: false
use_efficient: false
use_hr: false
use_swin: false
use_swinv2: false
warm_epoch: 5
weight_decay: 0.0005
